Exp creating main view
verapetriv/expense-app pull request #5
Opened 2022-04-05 06:31 UTC by verapetriv

2022-04-05 08:17 UTC, Velidoss requested changes

2022-04-05 08:17 UTC, Velidoss commented on src/components/TransactionsTable/TransactionsTable.tsx
> +              <StyledTableRow key={transaction.id}>
Цей компонент також краще відокремити.

2022-04-05 08:17 UTC, Velidoss commented on src/components/common/CommonModal.tsx
> +export const CommonModal: React.FC<CommonModalProps> = ({ isOpen, handleClose, content }) => {
Замість використання тут пропса content рекомендую скористатись children - це вбудований пропс в React - https://reactjs.org/docs/glossary.html#propschildren .

2022-04-05 08:17 UTC, Velidoss commented on src/components/common/SubmitButton.tsx
> +      {content}
Те ж саме. Краще юзати children.

2022-04-05 08:17 UTC, Velidoss commented on src/redux/transactionCategories/transactionCategoriesSlice.ts
> +      localStorageService.setCategories(state.transactionCategories);
Не викликай запити в localStorage з action. Це має робитись через thunk. Тут в тебе помилок нема, але в нашому випадку ls - це імітація бекенду, а запити виконуються в thunk.

2022-04-05 08:17 UTC, Velidoss commented on src/redux/transactionCategories/transactionCategoriesSlice.ts
> +export const getCategoryById = createDraftSafeSelector(
Наскільки пам'ятаю то цей селектор вже не використовується, вірно?)

2022-04-05 08:17 UTC, Velidoss commented on src/redux/transactions/transactionsSlice.ts
> +export const getFilteredTransactions = createDraftSafeSelector(
Ще я б порекомендував називати свої селектори з префіксом select замість get

2022-04-05 10:32 UTC, verapetriv commented on src/components/RenameCategoryForm/RenameCategoryForm.tsx
> +    const categoryData = {
я добавила изменение имени при `onBlure` и теперь код выглялит так 
```
  const onRename = (categoryData: NewCategory) => {
    dispatch(renameCategory(categoryData));
    onSubmitRenameCategory();
  };
```

```
  const onSubmit: SubmitHandler<InputType> = (data) => {
    const categoryData = {
      ...data,
      id: category.id,
    };

    onRename(categoryData);
  };

  const onBlur = (e: any) => {
    const categoryData = {
      newLabel: e.target.value,
      id: category.id,
    };
    onRename(categoryData);
  };
```
оставлять переменную `categoryData` или сразу в аргументами прокидывать?

2022-04-06 06:24 UTC, Velidoss approved these changes

2022-04-06 09:42 UTC, merged